# Generated by Django 3.1.1 on 2020-10-18 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201014_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorey',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
